### ISSUE TITLE
Deployment script

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ioboxd#2]
Create a deployment script (similar to ermrest/hatrac). The chaise team needs an example so that it can use that in its travisci test script to instantiate the ioboxd service.

**Comment by mikedarcy** [comment]
This already exists via the Makefile: 
```
sudo make deploy
```

Note: installation of `deriva-py` is a prerequisite for installing the service, and it is not installed automatically by the deployment script.
