### ISSUE TITLE
rsyslog logging

### ISSUE THREAD

**Issue by hongsudt** [informatics-isi-edu/ioboxd#3]
Can you log the ioboxd requests in rsyslog, similar to what ermrest/hatrac is doing? 

Chaise will send the export request log through the http header in the ioboxd requests. I would like this information to be logged, so we can use for analysis. 

Currently, syslogtag has ermrest, hatrac, webauthn as prefix. Maybe we can add ioboxd for ioboxd logs..

**Comment by mikedarcy** [comment]
Implemented in d7a943d66d1211243fca6ea952ac876de948feb4.
